### ISSUE TITLE
Does google authentication work

### ISSUE THREAD

**Issue by jcbowyer** [yagopv/DurandalAuth#33]
I can't get google or facebook authentication to work locally or on the sample site.  It seems that this is based partly on the code in the asp.net todos samples and I can't get it to work either.   I can get the stock mvc site sample to work for facebook authentication so it does not appear to be my clientid/secret.

**Comment by yagopv** [comment]
Hi,

The problem was with the Breeze Metadata method not working. I solved it recreating the database in the sample site because I upgraded Entity Framework nuget package.

In you dev environment you have to configure the oAuth providers to work with your localhost. The best way is to work with custom domain names and configure them in the oAuth console for each provider. 

In production now is working fine.

Thanks!!
